spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
            - Path=/books/**
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**
      http-client:
        #time limit for a connection to be established
        connect-timeout: 2000
        #time limit for a response to be received
        pool:
          #type of connection pool (elastic,fixed or disabled)
          type: elastic
          #Idle time after which the communication channel will be closed
          max-idle-time: 15s
          #Time after which the communication channel will be closed
          max-life-time: 60s
        response-timeout: 5s
      #A list of default filters
      default-filters:
        #The name of the filter
        - name: Retry
          args:
            #Maximum of 3 retry attempts
            retries: 3
            #Retries only GET requests
            methods: GET
            #Retries only when 5XX errors
            series: SERVER_ERROR
            #Retries only when the given Exceptions are thrown
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            #Retries with a delay computed as "firstBackoff *(factor ^ n)"
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
  lifecycle:
    timeout-per-shutdown-phase: 15s
server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful
